universe = docker
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable = /home/atml_team024/tml26_task3/run.sh
output = runlogs/task3.$(ClusterId).$(ProcId).out
error  = runlogs/task3.$(ClusterId).$(ProcId).err
log    = runlogs/task3.$(ClusterId).log
request_GPUs = 1
request_CPUs = 4
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
